# Generated by Django 4.2.7 on 2024-02-28 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promoters', '0003_promoter_common_name_promoter_full_name'),
    ]

    operations = [
    ]
