# Generated by Django 4.2.7 on 2024-02-29 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promoters', '0005_remove_promoter_first_name_remove_promoter_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='promoter',
            name='street_address',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
