# Generated by Django 4.2.7 on 2024-02-29 22:28

from django.db import migrations


def generalize_address(apps, schema_editor):
    Promoter = apps.get_model("promoters", "Promoter")
    for promoter in Promoter.objects.all():
        promoter.address = f"{promoter.street_address} {promoter.city} {promoter.state} {promoter.country}"
        promoter.save()

class Migration(migrations.Migration):


    dependencies = [
        ('promoters', '0010_promoter_address'),
    ]

    operations = [
        migrations.RunPython(
            generalize_address
        ),
    ]
