# Generated by Django 4.2.7 on 2024-02-29 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promoters', '0011_full_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promoter',
            name='city',
        ),
        migrations.RemoveField(
            model_name='promoter',
            name='country',
        ),
        migrations.RemoveField(
            model_name='promoter',
            name='state',
        ),
        migrations.RemoveField(
            model_name='promoter',
            name='street_address',
        ),
    ]
