# Generated by Django 4.2.7 on 2023-12-22 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0005_alter_room_room_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musician',
            name='first_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='musician',
            name='last_name',
            field=models.CharField(max_length=30),
        ),
    ]
