# Generated by Django 4.2.7 on 2024-02-04 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0007_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='venues_profiles',
            new_name='venue_profiles',
        ),
    ]
