# Generated by Django 4.2.7 on 2024-02-21 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0009_venue_description_venue_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musician',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
