# Generated by Django 4.2.7 on 2024-02-24 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0010_alter_musician_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='musician',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
