# Generated by Django 4.2.7 on 2024-02-14 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0008_rename_venues_profiles_userprofile_venue_profiles'),
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seekingad',
            name='band',
            field=models.ForeignKey(blank=True, help_text='Fill in if you are a band seeking a musician', null=True, on_delete=django.db.models.deletion.SET_NULL, to='bands.band'),
        ),
        migrations.AlterField(
            model_name='seekingad',
            name='musician',
            field=models.ForeignKey(blank=True, help_text='Fill in if you are a musician seeking a band', null=True, on_delete=django.db.models.deletion.SET_NULL, to='bands.musician'),
        ),
        migrations.AlterField(
            model_name='seekingad',
            name='seeking',
            field=models.CharField(choices=[('M', 'Musician'), ('B', 'Band')], help_text="I'm seeking a..", max_length=1),
        ),
    ]
